# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LBpXjg8_DgWzQ_f2aA3O-_ZufZnELUIc
"""

import sys 
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input
import tensorflow.keras as keras
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras import optimizers
import tensorflow as tf
from keras.utils import np_utils
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import cv2 
import random
from tensorflow.keras.models import model_from_json
from matplotlib import pyplot
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import array_to_img
from io import BytesIO
from skimage.transform import resize
from keras.preprocessing.image import ImageDataGenerator

#!/usr/bin/env python

def test(filepath):
  # Load trained CNN model
  json_file = open(r'C:\Users\yaoz\anaconda3\model_ver1.json', 'r')
  loaded_model_json = json_file.read()
  json_file.close()
  model = model_from_json(loaded_model_json)
  model.load_weights(r'C:\Users\yaoz\anaconda3\model_ver1.h5')

  path = filepath ##Change this for image path
  image = tf.keras.preprocessing.image.load_img(path, grayscale=False, color_mode='rgb', target_size=(320,320),interpolation='nearest')  
  array = tf.keras.preprocessing.image.img_to_array(image, data_format=None, dtype=None)
  array /= 255 
  array = np.resize(array,(1,320,320,3)) 

  top_k = 3 #Change to display more K classes 
  class_names = ["Bokeh","Romance","Depth of field","Detailed","Ethereal","Geometric Compression","Hazy","HDR","Long Exposure"]

  lst1=[]
  lst2=[] 
  top_values, top_indices = tf.nn.top_k(model.predict_on_batch(array[0]), k=top_k) 

  for i in range(0,top_k): 
    lst1.append(class_names[top_indices.numpy()[0][i]])
    lst2.append(top_values.numpy()[0][i]) 

  print(lst1)
  print(lst2)

if __name__ == "__main__":
    filepath = str(sys.argv[1])
    test(filepath)